FROM webhippie/python:latest-amd64

LABEL maintainer="Thomas Boerger <thomas@webhippie.de>" \
  org.label-schema.name="Ansible Later" \
  org.label-schema.vendor="Thomas Boerger" \
  org.label-schema.schema-version="1.0"

ENTRYPOINT [""]

ENV PY_COLORS=1

RUN apk update && \
  apk upgrade && \
  apk add libffi-dev openssl-dev && \
  pip3 install -U pip ansible-later && \
  apk del libffi-dev openssl-dev && \
  rm -rf /var/cache/apk/*
