FROM webhippie/python:latest

LABEL maintainer="Thomas Boerger <thomas@webhippie.de>" \
  org.label-schema.name="Ansible Later" \
  org.label-schema.vendor="Thomas Boerger" \
  org.label-schema.schema-version="1.0"

ENTRYPOINT ["/usr/bin/ansible-later"]

RUN apk update && \
  apk upgrade && \
  pip3 install -U pip ansible-later && \
  rm -rf /var/cache/apk/*
